apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-react-app
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/UzonduEgbombah/my-react-app-repo.git
    targetRevision: main
    path: /home/ubuntu/my-intern-app/kubernetes
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
